### ISSUE TITLE
my map is empty?

### ISSUE THREAD

**Issue by liamxg** [AntoineSoetewey/coronavirus_dashboard#1]
Dear @AntoineSoetewey ,

Please see below, thanks.

<img width="1162" alt="image" src="https://github.com/user-attachments/assets/1c324e3a-232d-4358-8724-74ba6fe18965" />

Best,
Liam

**Comment by AntoineSoetewey** [comment]
Dear @liamxg,

Using this [rmd file](https://github.com/AntoineSoetewey/coronavirus_dashboard/blob/master/coronavirus-dashboard.Rmd), it works on my machine.

Here is the output with no change in the code:

<img width="1822" alt="Screenshot 2024-12-24 at 12 43 10" src="https://github.com/user-attachments/assets/3eecd9c9-2f91-459d-919e-664476b51e8f" />

Regards,
Antoine

**Comment by AntoineSoetewey** [comment]
Dear @liamxg,

Same output on my machine.

The issue is probably due to a change in the functions used for the map. However, I don't maintain this dashboard anymore so I cannot help you this time.

Regards,
Antoine

(For reference: https://github.com/RamiKrispin/coronavirus_dashboard/issues/29)

**Comment by liamxg** [comment]
Dear @AntoineSoetewey ,

Thanks for your reply, only the map does not work for me, others are okay.

Best,

Liam

**Comment by AntoineSoetewey** [comment]
Same for me, unfortunately.

**Comment by liamxg** [comment]
Let me know if you'd like to troubleshoot together, maybe we can find a solution.

**Comment by AntoineSoetewey** [comment]
I cannot really spend time on this project right now, sorry for not being able to help you.

**Comment by liamxg** [comment]
I appreciate you letting me know. It’s totally fine, and I hope things calm down for you soon!
